### ISSUE TITLE
histogram.py:38 :: glob.glob(<imagepath>) fails for JPG

### ISSUE THREAD

**Issue by uvcyclotron** [alasin/Digital-Archive-CBIR#2]
Currently it takes only *.jpg files (extension case-sensitive). Fails for files with name: *.JPG. Fix required to make it accept either of those.

**Comment by alasin** [comment]
Fix: [4eee781](https://github.com/alasin/Digital-Archive-CBIR/commit/4eee78101a55c7539b3069882bc4fbe1c8696b65)
