### ISSUE TITLE
createvocab.cpp:95 :: allows non-image files to pass

### ISSUE THREAD

**Issue by uvcyclotron** [alasin/Digital-Archive-CBIR#4]
This check is not sufficient. Currently, this allows non-image files to pass into the imread() call, and error is thrown. Eg: for important directory files like .gitignore, and perhaps other residual files, this error occurs. Fix by adding check for image file.

**Comment by alasin** [comment]
[Fixed](https://github.com/alasin/Digital-Archive-CBIR/commit/a41ba879a72e8f6d71afeab2af69e649c94593c5).
