### ISSUE TITLE
libmagick++-dev not found

### ISSUE THREAD

**Issue by virajprabhu** [alasin/Digital-Archive-CBIR#5]
Since the client relies on imagemagick to generate thumbnails, I had to install libmagick++-dev (its C++ interface) with a `apt-get install libmagick++-dev`. 

This should be added to the documentation / packaged with the code.

**Comment by alasin** [comment]
[Fixed](https://github.com/alasin/Digital-Archive-CBIR/commit/4f2b06949d56a3ba367fcdb0bd2f48149743b5c9).
